
CREATE TABLE `order` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `shop_id` int(11) NOT NULL DEFAULT '0' COMMENT '店铺ID',
  `order_no` varchar(50) NOT NULL DEFAULT '' COMMENT '订单ID',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '订单状态 -2:维权完成 -1:已取消 0:待付款 1:待发货 2:待收货 3:已完成 ',
  `type` tinyint(2) NOT NULL DEFAULT '0' COMMENT '订单类型',
  `sub_type` tinyint(2) NOT NULL DEFAULT '0' COMMENT '订单子类型',
  `pay_type` int(10) NOT NULL DEFAULT '0' COMMENT '支付类型 2:余额支付 102:积分+余额',
  `member_id` int(11) NOT NULL DEFAULT '0' COMMENT '会员ID',
  `member_realname` varchar(64) NOT NULL DEFAULT '' COMMENT '会员真实姓名',
  `member_nickname` varchar(64) NOT NULL DEFAULT '' COMMENT '会员昵称',
  `member_mobile` varchar(20) DEFAULT NULL COMMENT '会员手机号',
  `pay_price` decimal(12,2) NOT NULL DEFAULT '0.00',
  `pay_credit` int(11) NOT NULL DEFAULT '0',
  `original_price` decimal(10,2) NOT NULL DEFAULT '0.00',
  `original_credit` int(11) NOT NULL DEFAULT '0',
  `dispatch_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '配送类型 0:无需快递 1:快递',
  `dispatch_price` decimal(10,2) NOT NULL DEFAULT '0.00',
  `original_dispatch_price` decimal(10,2) NOT NULL DEFAULT '0.00',
  `total_price` decimal(12,2) NOT NULL DEFAULT '0.00'  COMMENT '订单商品总价格',
  `original_total_price` decimal(10,2) NOT NULL DEFAULT '0.00'  COMMENT '订单商品总价格',

  `buyer_mobile` varchar(30) DEFAULT NULL COMMENT '收货人手机号',
  `buyer_name` varchar(64) NOT NULL DEFAULT '' COMMENT '收货人姓名',
  `address_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '收货人地址ID',
  `address_country` varchar(30) NOT NULL DEFAULT '' COMMENT '收货人所在国家',
  `address_province` varchar(10) NOT NULL DEFAULT '' COMMENT '收货人所在省份',
  `address_city` varchar(20) NOT NULL DEFAULT '' COMMENT '收货人所在城市',
  `address_area` varchar(30) NOT NULL DEFAULT '' COMMENT '收货人所在区',
  `address_detail` varchar(255) NOT NULL DEFAULT '' COMMENT '收货人详细地址',
  `comment_status` tinyint(1) NOT NULL DEFAULT '0',
  
  `create_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '下单时间',
  `pay_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '支付时间',
  `send_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '发货时间',
  `finish_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '完成时间',
  `close_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '关闭时间',
  `close_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '订单关单类型 0: 超时自动关闭 1:用户主动取消',
  `is_refund` tinyint(1) NOT NULL DEFAULT '0' COMMENT '订单是否维权',
  `refund_price` decimal(10,2) NOT NULL DEFAULT '0.00',
  `remark_buyer` varchar(255) NOT NULL DEFAULT '' COMMENT '买家备注',
  `remark_saler` varchar(255) NOT NULL DEFAULT '' COMMENT '卖家备注',
  `auto_close_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '自动关单时间',
  `auto_finish_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '自动确认收货时间',
  `payment_id` varchar(40) NOT NULL DEFAULT '',
  `pay_channel` smallint(4) NOT NULL DEFAULT '0',
  `member_level_id` int(11) NOT NULL DEFAULT '0' COMMENT '下单时会员等级',
  `member_tag_ids` varchar(128) DEFAULT NULL COMMENT '下单时会员标签集合',
  
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_order_no` (`order_no`),
  KEY `idx_member_id` (`member_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单表';


CREATE TABLE `es_shop_order_item` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `shop_id` int(11) NOT NULL DEFAULT '0' COMMENT '店铺ID',
  `order_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '订单ID',
  `product_id`bigint(20) NOT NULL DEFAULT '0' COMMENT '商品ID',
  `product_version` int(11) NOT NULL DEFAULT '0' COMMENT '商品版本号',
  `member_id` int(11) NOT NULL DEFAULT '0' COMMENT '会员ID',
  `status` int(11) NOT NULL DEFAULT '0' COMMENT '订单商品状态 0:未支付 1:已支付',
  `cash_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '实际付现金金额',
  `price_unit` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品售价（单价）',
  `price_original` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品划线价',
  `price_discount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品折扣（包括：积分+优惠券）',
  `cost_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品成本价',
  `coupon_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '抵扣优惠券金额',
  `deduct_credit` int(11) NOT NULL COMMENT '使用积分',
  `max_credit` int(11) NOT NULL COMMENT '最大可使用积分',
  `total` int(11) NOT NULL DEFAULT '1' COMMENT '购买数量数量',
  `title` varchar(255) NOT NULL DEFAULT '' COMMENT '商品名称',
  `option_id` int(11) NOT NULL DEFAULT '0' COMMENT '商品规格ID',
  `option_title` varchar(255) NOT NULL DEFAULT '' COMMENT '商品规格名称',
  `thumb` varchar(255) NOT NULL DEFAULT '' COMMENT '商品图片',
  `goods_code` varchar(255) NOT NULL DEFAULT '' COMMENT '商品编码',
  `refund_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '商品维权状态 0:未维权 1:维权中 2:维权完成',
  `refund_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '商品维权类型 0:未维权 1:仅退款 2:退货退款 3:换货',
  `refund_id` int(11) NOT NULL DEFAULT '0' COMMENT '商品维权记录ID，关联es_shop_order_refund表id',
  `package_id` int(11) NOT NULL DEFAULT '0' COMMENT '商品物流记录ID，关联es_shop_order_package表id ',
  `comment_status` tinyint(1) NOT NULL DEFAULT '0',

  `create_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_product_id` (`product_id`),
  KEY `idx_order_id` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单商品表';

