server:
  port: 8080

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/system_design_notes?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root2018
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 20
      minIdle: 1
      maxActive: 100
      maxWait: 5000
