server:
  port: 8080

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/system_design_notes?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root2018
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 20
      minIdle: 1
      maxActive: 100
      maxWait: 5000

  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 5s
    lettuce:
      pool:
        min-idle: 0
        max-active: 20
        max-idle: 8
        max-wait: -1ms